### ISSUE TITLE
Unset default values on prompt on launch fields

### ISSUE THREAD

**Issue by EliasBoulharts** [schubergphilis/towerlib#106]
We must unset value or set value to false for some parameters of job launch. ([See the commit](https://github.com/schubergphilis/towerlib/pull/105/commits/0f9a71b22f655f7bee73cb5911f3b6edb224fa15))

**Comment by Sispheor** [comment]
An example of usage::

If for example a Job Template is set with some tags. 
Using the lib with tags="" is not sent and so the default config is kept instead of executing the playbook without any tags.
