### ISSUE TITLE
Version 3.12.1 should not have been pushed on main

### ISSUE THREAD

**Issue by dangoncalves** [schubergphilis/towerlib#117]
Version 3.12.1 seems to be released (the tag was published March, 29th 2023), but tests does not passes. It's a little bit confusing while documentation states that this version exists, but CI build step failed on tests and it wasn't published on pypi.

**Comment by costastf** [comment]
You are indeed right, this was a testing tag that should be reverted. I will do that during next week, thanks for reporting!

**Comment by costastf** [comment]
We are also in the prices of seeing up the tests again so the pipeline is green and works as expected, that is WIP and should take some time though.

**Comment by costastf** [comment]
Commit reverted and actually released v3.13.0 with an improvement in adding timeout for requests.
