### ISSUE TITLE
Feature Request: self-signed certificate authority support?

### ISSUE THREAD

**Issue by ericoc** [schubergphilis/towerlib#19]
From what I can tell, I don't see this as a current feature within towerlib. I think it would be awesome if towerlib supported self-signed HTTPS SSL certificates.

For example, my Ansible Tower installation is on my local network. It uses a certificate that I signed with the internal certificate authority that I have created. I would love to be able to reference my certificate authority when calling towerlib; something like:

```
from towerlib import Tower

# using https with a self-signed certificate
tower = Tower('ansible.internal.ericoc.com', 'eric', 'password', secure=True, ssl_verify=True, ssl_cacert='/etc/ssl/certs/internal.ericoc.com.ca.crt')
````

The [python-requests documentation](https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification) makes me think that this should theoretically be possible, but I am no Python expert.

Thanks in advance for the consideration - cheers!

**Comment by ericoc** [comment]
I actually just discovered that this works as-is! It appears that setting `ssl_verify` to a string value that is the path of the certificate authority (along with `secure=true`) is okay.

This works perfectly fine:
```
from towerlib import Tower

# using https with a self-signed certificate
tower = Tower('ansible.internal.ericoc.com', 'eric', 'password', secure=True, ssl_verify='/etc/ssl/certs/internal.ericoc.com.ca.crt')
```

It should probably just be documented.

**Comment by costastf** [comment]
Hi, sorry for not replying earlier. ssl_verify is used as in requests and it gets transparently passed along the session so it works just fine as you figured out. :) it would be wonderful if you made a merge request with the documentation change that you think would help clarify this.

**Comment by ericoc** [comment]
Will do - cheers!

**Comment by costastf** [comment]
Lovely, thanks!
