### ISSUE TITLE
ConnectionError on job template relative credential

### ISSUE THREAD

**Issue by gthieleb** [schubergphilis/towerlib#21]
Using towerlib version from pip:

```
$ pip list|grep tower
towerlib           2.3.4    
```

When fetching a job template and trying to receive the credential for the job template this fails with a `ConnectionError`:

```
t = Tower('awx2.admin.lab', 'admin', '*******')
base_job_template = t.get_job_template_by_name('vm-expansion-template')
base_job_template.project                                                                                                                                                                                                
<towerlib.entities.project.Project at 0x7fd2bb167668>

base_job_template.credential                                                                                                                                                                                             

~/.virtualenvs/airflow/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='awx2.admin.labnone', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2bb01f7b8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

The URL instead of `awx2.admin.labnone` should be `awx2.admin.lab`. I don't know why the `none` is appended.

**Comment by costastf** [comment]
Should be fixed with v2.3.5 just uploaded. Please validate and close.

**Comment by gthieleb** [comment]
Works for me.

**Comment by costastf** [comment]
There will be a new major version out that changes this, since this fix was incomplete. The credential object is removed and only a credentials entity manager is exposed that gives access to all credentials since awx has dropped the single credential attribute. Just FYI.

**Comment by gthieleb** [comment]
thx for the headup. I did not tested this, yet. 
indeed will have a need this week. 
good Timing!

**Comment by gthieleb** [comment]
@costastf There is `credential` (singular) in  `create_job_template`, assuming that [this](
https://github.com/schubergphilis/towerlib/blob/fa8faaa7ca377b94e2b97853239e34713fef4912/towerlib/towerlib.py#L436) is the current branch you are working on.

**Comment by costastf** [comment]
I am sorry but i do not understand the issue here. Can you please elaborate?

**Comment by gthieleb** [comment]
According to this
> ... since awx has dropped the single credential attribute.

my naive assumption is there should now be a `credentials` properterty instead of `credential` for `create_job_template`.

**Comment by costastf** [comment]
Ah, i get it. No that is not what I meant. Up until now the job_template had a credential attribute that pointed to the default credential and a credentials attribute that pointed to all of the credentials used. Awx has dropped the credential attribute since it is not really needed as from the list of the credentials only one is always the default one. I will check when implementing the latest changes if that changes the signature of the method mentioned where it can now accept more than one and make sure that it is aligned. I expect the new version to be out some time early next week.
