### ISSUE TITLE
add support for cloud credential type

### ISSUE THREAD

**Issue by gthieleb** [schubergphilis/towerlib#28]
It would be a big improvement to have the ability to attach credential of type `cloud` to a job template via api call.

Currently its only possible to use `machine`  credentials with the single  `credential` property in `job_template`. Other credentials types are not supported. The single `credential` type is subject to delete¹.

The proper way to to attach credentials of other types would be to use the following endpoint after the job template has been created:

```
/api/v2/job_templates/<id>/credentials/
```
A simple payload containing the credential id is neccessary:

```
{'id': 3}
```

¹ https://github.com/ansible/awx/pull/3413

**Comment by costastf** [comment]
Hi @gthieleb, thanks for reporting. I don't think you are correct, looking at the code of the template creation it only expects a credential name and it is not specified what type it is, so it could be any type. We are currently quite busy with a big refactoring of the code and will make a new major release some time this week and I will definitely validate if this is an issue or not.

**Comment by gthieleb** [comment]
Hi @costastf thanks for your update.
I can reproduce the behavior that AWX cares about the credential type:

```
In [1]: i = t.get_inventory_by_name('test')                                                                                                                                                                                     

In [2]: b = t.get_job_template_by_name('vm-expansion-template')                                                                                                                                                                  

In [3]: c = t.get_credential_by_name("ovirtm.admin.lab")                                                                                                                                                                         

# non machine credential type
In [4]: c.credential_type.name                                                                                                                                                                                                   
Out[4]: 'Red Hat Virtualization'

In [5]: payload = dict(name='test', description='test', inventory=i.id, project=b.project.id, playbook=b.playbook, credential=c.id)                                                                                              

In [6]: response = t.session.post(url, data=json.dumps(payload))                                                                                                                                                                 

In [7]: response.text                                                                                                                                                                                                            
Out[7]: '{"credential":["You must provide an SSH credential."]}'
```
From my findings credential type `machine` was the only one supported in APIv1 with the `credential` property.

As I am fairly new to AWX/Tower API this assumption might be wrong so please correct me.

**Comment by gthieleb** [comment]
Is there anything I can do with test or help on this?

**Comment by costastf** [comment]
Hi @gthieleb , no, not really thanks though! We ended up doing a huge refactoring of the code and I am currently busy with writing integration tests for the new code. I am almost at 60% and the refactoring was much bigger than initially planned so it is going to take at least a couple of more weeks before I can release a stable version. Apologies, but I do hope that the wait is going to be worth it.

**Comment by costastf** [comment]
This should be handled with the latest v3 release.
