### ISSUE TITLE
credential should become an optional argument for job template

### ISSUE THREAD

**Issue by gthieleb** [schubergphilis/towerlib#29]
The `credential` attribtue should become an optional argument for `create_job_template`. 

Why? 
Currently only credential type `machine` are supported. There are use cases where job template do not care about credential variables.

IMO there are two possibilities. 

1. Keep the `credential` property as long it's supported by the AWX api but make it optional.
2. Keep the `credential` as required but make it accept `None`.

The introduction of `credentials` property (plural) (see #28) should be kept seperated from this.

**Comment by costastf** [comment]
This should be handled with the latest v3 release.
