### ISSUE TITLE
Python version compatibility

### ISSUE THREAD

**Issue by phospi** [schubergphilis/towerlib#52]
Hi there,

I got an issue with the pipfile and python version compatibility. I know that this package is mainly written for python 3.7 and I had a look if I could run this code with python 3.6. As far as I can tell it worked, but still I noticed a very special case of package dependency. For python 3.6 there is a pip package for "dataclasses" which is not necessary for python 3.7.

To reflect this requirement, I can write the following line into the pipfile:
```
[packages]
dataclasses = { version = "==0.6", markers="python_version == 3.7" }
```

Such usage of pipfile is described here: https://pipenv-fork.readthedocs.io/en/latest/advanced.html

However, by doing so, the code in _CI/library/core_library.py breaks. It seems to me, that it can't handle a package dict.

**Comment by costastf** [comment]
v3.2.8 fixes the marker handling, along with removing some unwanted development packages and adding the dataclasses package with a marker to add 3.6 compatibility. Thanks for reporting!
