### ISSUE TITLE
__init__() got an unexpected keyword argument 'token'

### ISSUE THREAD

**Issue by MahdiSMIDA** [schubergphilis/towerlib#71]
tower = Tower('ansible.domain.com', None, None, secure=True, token="token-data-here")
TypeError: __init__() got an unexpected keyword argument 'token'

**Comment by costastf** [comment]
Please make sure you are using the latest version of the library.

**Comment by costastf** [comment]
@MahdiSMIDA did you try with the latest version of the library?
