### ISSUE TITLE
Feature request: Link the survey spec to the job template when exist

### ISSUE THREAD

**Issue by Sispheor** [schubergphilis/towerlib#75]
The current JobTemplate object only return a bool `survey_enabled`.

It would be nice to retrieve [the full survey spec](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Job_Templates/Job_Templates_job_templates_survey_spec_list).

**Comment by costastf** [comment]
Hi @Sispheor is this still relevant? I think that this feature was merged right? If so could you please close this issue? Thanks!

**Comment by Sispheor** [comment]
Yep we can close it. Thanks.
