### ISSUE TITLE
Usage documentation does not include filtering exmaples

### ISSUE THREAD

**Issue by SimonGurney** [schubergphilis/towerlib#78]
Hi,

I have raise a PR (#77) to update the USAGE docs as the filtering implementation is really easy to use but is not covered on the USAGE page.

In my use case, iterating all "successful" jobs was significantly quicker using the filter via the API then making thousands of API calls and filtering upon their receipt with Python.  I think this is such as common use case it should have a little coverage in the USAGE page as I had to look through the source code to find it.

**Comment by costastf** [comment]
Thank you very much, the documentation indeed can use a lot of love. There is a lot of functionality covered that is not documented. This MR is greatly appreciated and please feel free to do more ☺️
