### ISSUE TITLE
towerlib.entities import error

### ISSUE THREAD

**Issue by Easin666** [schubergphilis/towerlib#83]
![Uploading 924F3DCD-CA7C-4A86-B5A7-F9DFF38FBA3C.jpeg…]()
Hello, could you pls suggest why I encounter error “no muddle towerlib found” happened on attached snippet.
 Per my understanding, entities is a package not module, how can we use like that? I am freshman for python and confused for that. Appreciated.

**Comment by Easin666** [comment]
error happened on core.py.
module = __import__(‘towerlib.entities’)

**Comment by costastf** [comment]
Hi @Easin666 there is no screenshot attached so i can't really help you. If you post the code you are using i might be able to help.

**Comment by phospi** [comment]
@Easin666 from the few detaisl you provide it looks like your import statement is wrong.

Please have look at the usage documentation for proper import and initialization: https://towerlib.readthedocs.io/en/latest/usage.html

**Comment by costastf** [comment]
Thank you @phospi !

**Comment by Easin666** [comment]
> Hi @Easin666 there is no screenshot attached so i can't really help you. If you post the code you are using i might be able to help.

Hi costastf, does this project build on Unix OS? Not sure if it’s running smoothly on windows, maybe that why I got import error using the identical source code.

**Comment by costastf** [comment]
Hi @Easin666 you need to help me help you. You are not providing any info and you question worries me a little? What do you mean does the project build on Unix? How are you installing it? Here https://towerlib.readthedocs.io/en/latest/installation.html you can read how you should install the library. Here https://towerlib.readthedocs.io/en/latest/usage.html you can see some basic usage. Here https://towerlib.readthedocs.io/en/latest/modules.html you can see all the modules and what they do and how to use them. Please provide more details on how you install, what you are trying and what fails so i can help you.
